name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v6

    - name: Build and push the visualization 
      uses: docker/build-push-action@master
      with:
        context: ./services/visualization
        push: true
        tags: ${{secrets.GCP_ARTIFACT_REGISTRY}}:latest

    - name: Build and push the control screen
      uses: docker/build-push-action@master
      with:
        context: ./services/mobile control screen
        push: true
        tags: ${{secrets.GCP_ARTIFACT_REGISTRY}}:latest
